---
apiVersion: v1
kind: Secret
metadata:
  name: repocreds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: ssh://git@github.com/KestutisKazlauskas/kong-with-metrics-deployment.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    Change this to private key
    -----END OPENSSH PRIVATE KEY-----
  insecure: "false"
  enableLfs: "false"